// playgrounds/nuxt3/components/SiteNav.vue
<template>
  <nav class="site-nav">
    <span class="brand">quello</span>
    <NuxtLink to="/" active-class="active">Overview</NuxtLink>
    <NuxtLink to="/gallery" active-class="active">Gallery</NuxtLink>
    <NuxtLink to="/article" active-class="active">Article</NuxtLink>
    <span class="spacer" />
    <span class="hint">Alt+Q to pick</span>
  </nav>
</template>

// playgrounds/react19/src/components/SiteNav.tsx
import { NavLink } from 'react-router-dom'

const linkClass = ({ isActive }: { isActive: boolean }) => (isActive ? 'active' : '')

export function SiteNav() {
  return (
    <nav className="site-nav">
      <span className="brand">quello</span>
      <NavLink to="/" className={linkClass} end>
        Overview
      </NavLink>
      <NavLink to="/gallery" className={linkClass}>
        Gallery
      </NavLink>
      <NavLink to="/article" className={linkClass}>
        Article
      </NavLink>
      <span className="spacer" />
      <span className="hint">Alt+Q to pick</span>
    </nav>
  )
}
