// playgrounds/svelte/src/App.svelte
<script lang="ts">
  import SiteNav from './components/SiteNav.svelte'
  import OverviewPage from './pages/OverviewPage.svelte'
  import GalleryPage from './pages/GalleryPage.svelte'
  import ArticlePage from './pages/ArticlePage.svelte'
  import { router } from './router.svelte'
</script>

<SiteNav />
{#if router.path === '/gallery'}
  <GalleryPage />
{:else if router.path === '/article'}
  <ArticlePage />
{:else}
  <OverviewPage />
{/if}
<footer class="site-footer">
  quello · Svelte playground — three routes, all of them longer than the viewport.
</footer>

// playgrounds/react/src/App.tsx
import { useEffect } from 'react'
import { Route, Routes, useLocation } from 'react-router-dom'
import { SiteNav } from './components/SiteNav'
import { OverviewPage } from './pages/OverviewPage'
import { GalleryPage } from './pages/GalleryPage'
import { ArticlePage } from './pages/ArticlePage'

const TITLES: Record<string, string> = {
  '/': 'Overview',
  '/gallery': 'Gallery',
  '/article': 'Article',
}

export function App() {
  const { pathname } = useLocation()

  // The pick's `page.title` should differ per route, so keep the document title in step.
  useEffect(() => {
    document.title = `${TITLES[pathname] ?? 'Not found'} · quello React playground`
    window.scrollTo(0, 0)
  }, [pathname])

  return (
    <>
      <SiteNav />
      <Routes>
        <Route path="/" element={<OverviewPage />} />
        <Route path="/gallery" element={<GalleryPage />} />
        <Route path="/article" element={<ArticlePage />} />
      </Routes>
      <footer className="site-footer">
        quello · React playground — three routes, all of them longer than the viewport.
      </footer>
    </>
  )
}
