// playgrounds/vue/src/components/CardList.vue
<script setup lang="ts">
import CardItem from './CardItem.vue'

const cards = [
  { title: 'Selector', body: 'Unique CSS selector for every pick.' },
  { title: 'Component', body: 'Vue component name and source file.' },
  { title: 'Persistence', body: 'Written to .quello/picks.json by the dev server.' },
]
</script>

<template>
  <section class="card-list">
    <CardItem v-for="card in cards" :key="card.title" :title="card.title" :body="card.body" />
  </section>
</template>

// playgrounds/react/src/components/CardList.tsx
import { CardItem } from './CardItem'

const cards = [
  { title: 'Selector', body: 'Unique CSS selector for every pick.' },
  { title: 'Component', body: 'React component name from the fiber tree.' },
  { title: 'Persistence', body: 'Written to .quello/picks.json by the dev server.' },
]

export function CardList() {
  return (
    <section className="card-list">
      {cards.map((card) => (
        <CardItem key={card.title} title={card.title} body={card.body} />
      ))}
    </section>
  )
}
