// playgrounds/react19/src/components/TokenTile.tsx
export function TokenTile({ name, group, hue }: { name: string; group: string; hue: number }) {
  return (
    <article className="tile">
      <div className="swatch" style={{ background: `hsl(${hue} 55% 42%)` }} />
      <div className="body">
        <h3>{name}</h3>
        <p>{group}</p>
      </div>
    </article>
  )
}

// playgrounds/nuxt4/app/components/TokenTile.vue
<script setup lang="ts">
const props = defineProps<{ name: string; group: string; hue: number }>()
</script>

<template>
  <article class="tile">
    <div class="swatch" :style="{ background: `hsl(${props.hue} 55% 42%)` }" />
    <div class="body">
      <h3>{{ name }}</h3>
      <p>{{ group }}</p>
    </div>
  </article>
</template>
