// playgrounds/react18/src/pages/OverviewPage.tsx
import { useState } from 'react'
import { FeatureCard } from '../components/FeatureCard'
import { features, sections } from '../content'

export function OverviewPage() {
  const [clicks, setClicks] = useState(0)

  return (
    <main className="page">
      <header className="hero">
        <h1>Point at it, then say "quello"</h1>
        <p className="lead">
          A visual element picker for AI coding agents. Toggle picker mode with <code>Alt+Q</code>,
          click anything, and the pick lands in <code>.quello/picks.json</code>.
        </p>
        <div className="badge-row">
          <span className="pill">React 18</span>
          <span className="pill">react-router</span>
          <span className="pill">3 routes</span>
          <span className="pill">sticky nav + rail</span>
        </div>
        <div className="actions">
          <button className="cta" onClick={() => setClicks((n) => n + 1)}>
            Clicked {clicks} times
          </button>
          <button className="ghost">Secondary action</button>
        </div>
      </header>

      <h2>What a pick carries</h2>
      <section className="grid">
        {features.map((feature) => (
          <FeatureCard key={feature.title} {...feature} />
        ))}
      </section>

      <div className="split" style={{ marginTop: 48 }}>
        <aside className="rail">
          {sections.map((section) => (
            <a key={section.id} href={`#${section.id}`}>
              {section.title}
            </a>
          ))}
        </aside>
        <div>
          {sections.map((section) => (
            <section key={section.id} id={section.id}>
              <h2 style={{ marginTop: 0 }}>{section.title}</h2>
              {section.paragraphs.map((paragraph, index) => (
                <p key={index}>{paragraph}</p>
              ))}
            </section>
          ))}
        </div>
      </div>
    </main>
  )
}

// playgrounds/vue/src/pages/OverviewPage.vue
<script setup lang="ts">
import { ref } from 'vue'
import FeatureCard from '../components/FeatureCard.vue'
import { features, sections } from '../content'

const clicks = ref(0)
</script>

<template>
  <main class="page">
    <header class="hero">
      <h1>Point at it, then say "quello"</h1>
      <p class="lead">
        A visual element picker for AI coding agents. Toggle picker mode with <code>Alt+Q</code>,
        click anything, and the pick lands in <code>.quello/picks.json</code>.
      </p>
      <div class="badge-row">
        <span class="pill">Vue 3</span>
        <span class="pill">vue-router</span>
        <span class="pill">3 routes</span>
        <span class="pill">sticky nav + rail</span>
      </div>
      <div class="actions">
        <button class="cta" @click="clicks++">Clicked {{ clicks }} times</button>
        <button class="ghost">Secondary action</button>
      </div>
    </header>

    <h2>What a pick carries</h2>
    <section class="grid">
      <FeatureCard
        v-for="feature in features"
        :key="feature.title"
        :title="feature.title"
        :body="feature.body"
        :tag="feature.tag"
      />
    </section>

    <div class="split" style="margin-top: 48px">
      <aside class="rail">
        <a v-for="section in sections" :key="section.id" :href="`#${section.id}`">
          {{ section.title }}
        </a>
      </aside>
      <div>
        <section v-for="section in sections" :id="section.id" :key="section.id">
          <h2 style="margin-top: 0">{{ section.title }}</h2>
          <p v-for="(paragraph, index) in section.paragraphs" :key="index">{{ paragraph }}</p>
        </section>
      </div>
    </div>
  </main>
</template>
