// playgrounds/react18/src/App.tsx
import { useEffect } from 'react'
import { Route, Routes, useLocation } from 'react-router-dom'
import { SiteNav } from './components/SiteNav'
import { OverviewPage } from './pages/OverviewPage'
import { GalleryPage } from './pages/GalleryPage'
import { ArticlePage } from './pages/ArticlePage'

const TITLES: Record<string, string> = {
  '/': 'Overview',
  '/gallery': 'Gallery',
  '/article': 'Article',
}

export function App() {
  const { pathname } = useLocation()

  // The pick's `page.title` should differ per route, so keep the document title in step.
  useEffect(() => {
    document.title = `${TITLES[pathname] ?? 'Not found'} · quello React 18 playground`
    window.scrollTo(0, 0)
  }, [pathname])

  return (
    <>
      <SiteNav />
      <Routes>
        <Route path="/" element={<OverviewPage />} />
        <Route path="/gallery" element={<GalleryPage />} />
        <Route path="/article" element={<ArticlePage />} />
      </Routes>
      <footer className="site-footer">
        quello · React 18 playground — three routes, all of them longer than the viewport.
      </footer>
    </>
  )
}

// playgrounds/solid/src/App.tsx
import { createEffect } from 'solid-js'
import { useLocation } from '@solidjs/router'
import type { ParentProps } from 'solid-js'
import { SiteNav } from './components/SiteNav'

const TITLES: Record<string, string> = {
  '/': 'Overview',
  '/gallery': 'Gallery',
  '/article': 'Article',
}

export function App(props: ParentProps) {
  const location = useLocation()

  createEffect(() => {
    document.title = `${TITLES[location.pathname] ?? 'Not found'} · quello Solid playground`
    window.scrollTo(0, 0)
  })

  return (
    <>
      <SiteNav />
      {props.children}
      <footer class="site-footer">
        quello · Solid playground — three routes, all of them longer than the viewport.
      </footer>
    </>
  )
}
