// playgrounds/react/src/main.tsx
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import { App } from './App'
import './style.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </StrictMode>,
)

// playgrounds/solid/src/main.tsx
import { render } from 'solid-js/web'
import { Router, Route } from '@solidjs/router'
import { App } from './App'
import { OverviewPage } from './pages/OverviewPage'
import { GalleryPage } from './pages/GalleryPage'
import { ArticlePage } from './pages/ArticlePage'
import './style.css'

render(
  () => (
    <Router root={App}>
      <Route path="/" component={OverviewPage} />
      <Route path="/gallery" component={GalleryPage} />
      <Route path="/article" component={ArticlePage} />
    </Router>
  ),
  document.getElementById('root')!,
)
